


















 


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `V21ConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=192.168.1.5;Initial Catalog=V21;User ID=DEV;Password=DEVDEV`
//     Schema:                 ``
//     Include Views:          `True`

//     Factory Name:          `SqlClientFactory`
using System;
using System.Data.Common;
using System.Data;
using System.Collections.Generic;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;

namespace oze.data
{
	public static class SPList 
	{
		private static DbParameter CreateNewParameter(DbCommand dbCommand, string paramName, object paramValue, ParameterDirection paramDirection, DbType paramType)
		{
			DbParameter param = dbCommand.CreateParameter();
			param.Direction = paramDirection;
			param.DbType = paramType;
			param.ParameterName = paramName;
			param.Value = paramValue ?? DBNull.Value;
			return param;
		}

		public static OrmLiteSPStatement sp_Select_Provider_By_DistributorsID(this IDbConnection db, int? @distributorsID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Provider_By_DistributorsID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DistributorsID",@distributorsID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ParentCategory_By_ProviderID(this IDbConnection db, int? @providerID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ParentCategory_By_ProviderID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ExportCoupon_SelectPaging(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, string @srcNetworkCode = null, string @desNetworkCode = null, string @userName = null, int? @networkID = null, int? @pageIndex = null, int? @pageSize = null, byte? @status = null, string @orderCode = null, int? @recordCount = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ExportCoupon_SelectPaging";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SrcNetworkCode",@srcNetworkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DesNetworkCode",@desNetworkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkID",@networkID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageIndex",@pageIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageSize",@pageSize,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Byte));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderCode",@orderCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RecordCount",@recordCount,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Store_Import(this IDbConnection db, string @searchText = null, int? @networkID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Store_Import";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkID",@networkID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Deposit_GetNetWorkname(this IDbConnection db, string @networkCode = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Deposit_GetNetWorkname";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Core_ConfigProviderProduct_Check_Product_Provider(this IDbConnection db, string @providerID = null, int? @productID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Core_ConfigProviderProduct_Check_Product_Provider";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ExportCoupon_Detail_By_ID(this IDbConnection db, int? @orderID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ExportCoupon_Detail_By_ID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderID",@orderID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Product_By_StoreExport_NCC(this IDbConnection db, int? @storeID = null, string @searchText = null, int? @providerID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Product_By_StoreExport_NCC";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreID",@storeID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_PromotionDiscountProduct_Select_Product(this IDbConnection db, int? @providerID = null, int? @distributorsID = null, int? @parentCategoryID = null, int? @trademarkID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_PromotionDiscountProduct_Select_Product";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DistributorsID",@distributorsID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"TrademarkID",@trademarkID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SearchAll_Product2(this IDbConnection db, string @searchText = null, int? @providerId = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SearchAll_Product2";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderId",@providerId,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GetProduct3(this IDbConnection db, string @productId = null, int? @storeCode = null, string @network = null, int? @providerId = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GetProduct3";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"productId",@productId,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreCode",@storeCode,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"network",@network,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderId",@providerId,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_CostBouns_ViewPromotionDiscountProduct(this IDbConnection db, int? @costBounsID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_CostBouns_ViewPromotionDiscountProduct";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CostBounsID",@costBounsID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Search_Product(this IDbConnection db, int? @providerID = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Search_Product";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_KhuyenMaiMua_QuaTangKem(this IDbConnection db, int? @costBounsID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_KhuyenMaiMua_QuaTangKem";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CostBounsID",@costBounsID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GetOderProductNPP_NCC(this IDbConnection db, string @productId = null, string @network = null, int? @providerid = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GetOderProductNPP_NCC";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"productId",@productId,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"network",@network,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"providerid",@providerid,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Core_OrderInput_By_Id(this IDbConnection db, int? @orderID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Core_OrderInput_By_Id";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderID",@orderID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_PromotionDiscountProduct_Network(this IDbConnection db, string @networkCode = null, string @level = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_PromotionDiscountProduct_Network";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Level",@level,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectAll_Order_Paging_NCC(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, int? @providerID = null, int? @storeID = null, int? @networkID = null, int? @pageIndex = null, int? @pageSize = null, int? @recordCount = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectAll_Order_Paging_NCC";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreID",@storeID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkID",@networkID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageIndex",@pageIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageSize",@pageSize,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RecordCount",@recordCount,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SearchAll_Product(this IDbConnection db, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SearchAll_Product";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Filter_Category(this IDbConnection db, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Filter_Category";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectAll_Unit_By_ProductID(this IDbConnection db, int? @productID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectAll_Unit_By_ProductID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Filter_Product(this IDbConnection db, string @searchText = null, int? @categoryID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Filter_Product";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CategoryID",@categoryID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_View_Core_Order_By_OrderCode(this IDbConnection db, string @orderCode = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_View_Core_Order_By_OrderCode";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderCode",@orderCode,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Core_OrderInputDetail_By_OrderID(this IDbConnection db, int? @orderID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Core_OrderInputDetail_By_OrderID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderID",@orderID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_View_ChiTietPhieuXuatDonDat_ChoXuatKho_By_OrderID(this IDbConnection db, int? @orderId = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_View_ChiTietPhieuXuatDonDat_ChoXuatKho_By_OrderID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderId",@orderId,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ExportCoupon_SelectPaging_NCC(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, int? @providerID = null, string @srcNetworkCode = null, string @desNetworkCode = null, string @userName = null, int? @networkID = null, int? @pageIndex = null, int? @pageSize = null, int? @recordCount = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ExportCoupon_SelectPaging_NCC";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SrcNetworkCode",@srcNetworkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DesNetworkCode",@desNetworkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkID",@networkID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageIndex",@pageIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageSize",@pageSize,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RecordCount",@recordCount,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Deposit_Search_DepositCode(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, string @networkCode = null, string @networkCodePoint = null, int? @networkIdNguoiThu = null, string @depositCode = null, int? @status = null, string @networkCodeDefault = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Deposit_Search_DepositCode";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCodePoint",@networkCodePoint,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkIdNguoiThu",@networkIdNguoiThu,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DepositCode",@depositCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCodeDefault",@networkCodeDefault,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_DepositDetail_By_DepositID(this IDbConnection db, int? @depositID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_DepositDetail_By_DepositID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DepositID",@depositID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_LoginFilter(this IDbConnection db, string @nameFunction = null, DateTime? @dfrom = null, DateTime? @dto = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_LoginFilter";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NameFunction",@nameFunction,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Dfrom",@dfrom,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Dto",@dto,ParameterDirection.Input,DbType.DateTime));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_CheckDaXuatKhoHangDiDuong(this IDbConnection db, string @networkCodeNutXuat = null, string @networkCodeNutNhap = null, string @networkCodeUserName = null, bool? @isXuatKhoHangDiDuong = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_CheckDaXuatKhoHangDiDuong";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCodeNutXuat",@networkCodeNutXuat,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCodeNutNhap",@networkCodeNutNhap,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCodeUserName",@networkCodeUserName,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"IsXuatKhoHangDiDuong",@isXuatKhoHangDiDuong,ParameterDirection.InputOutput,DbType.Boolean));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Deposit_By_DepositID(this IDbConnection db, int? @depositID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Deposit_By_DepositID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DepositID",@depositID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ReportSalePriceManagement(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, int? @productID = null, int? @groupProductID = null, int? @categoryID = null, int? @parentCategoryID = null, int? @unitID = null, string @barcode = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ReportSalePriceManagement";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupProductID",@groupProductID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CategoryID",@categoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UnitID",@unitID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Barcode",@barcode,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GetProduct(this IDbConnection db, string @productId = null, string @orderDetailId = null, int? @startIndex = null, int? @endIndex = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GetProduct";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"productId",@productId,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderDetailId",@orderDetailId,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"startIndex",@startIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"endIndex",@endIndex,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ReportImportPriceManage(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, int? @productID = null, int? @groupProductID = null, int? @categoryID = null, int? @parentCategoryID = null, int? @unitID = null, string @barcode = null, int? @providerID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ReportImportPriceManage";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupProductID",@groupProductID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CategoryID",@categoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UnitID",@unitID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Barcode",@barcode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ExportCoupon_Check_ProductImportExcel(this IDbConnection db, string @productCode = null, string @productName = null, string @unitName = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ExportCoupon_Check_ProductImportExcel";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductCode",@productCode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductName",@productName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UnitName",@unitName,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GetProductByOrderWaitExportStore(this IDbConnection db, string @orderId = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GetProductByOrderWaitExportStore";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderId",@orderId,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GetTotalProduct(this IDbConnection db, string @productId = null, string @orderDetailId = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GetTotalProduct";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"productId",@productId,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderDetailId",@orderDetailId,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_View_ChiTietPhieuXuatDonDat_DaXuatKho_By_OrderID(this IDbConnection db, int? @orderId = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_View_ChiTietPhieuXuatDonDat_DaXuatKho_By_OrderID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderId",@orderId,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_GroupProduct_By_CategoryID_New(this IDbConnection db, int? @providerID = null, int? @parentCategoryID = null, int? @categoryID = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_GroupProduct_By_CategoryID_New";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CategoryID",@categoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Core_CustomerDiscount_Insert(this IDbConnection db, int? @networkID = null, decimal? @discount = null, decimal? @discountPoint = null, decimal? @discountX1 = null, decimal? @discountX = null, string @levelType = null, string @receivedLevel = null, int? @status = null, int? @productID = null, int? @parentCategoryID = null, DateTime? @fromDate = null, DateTime? @toDate = null, string @userCreated = null, string @type = null, string @systemType = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Core_CustomerDiscount_Insert";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkID",@networkID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Discount",@discount,ParameterDirection.Input,DbType.Decimal));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DiscountPoint",@discountPoint,ParameterDirection.Input,DbType.Decimal));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DiscountX1",@discountX1,ParameterDirection.Input,DbType.Decimal));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DiscountX",@discountX,ParameterDirection.Input,DbType.Decimal));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"LevelType",@levelType,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ReceivedLevel",@receivedLevel,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserCreated",@userCreated,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Type",@type,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SystemType",@systemType,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GetInfo_Product(this IDbConnection db, int? @storeID = null, int? @productID = null, int? @unitID = null, int? @detailType = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GetInfo_Product";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreID",@storeID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UnitID",@unitID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DetailType",@detailType,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Product_By_GroupProductID_New(this IDbConnection db, int? @providerID = null, int? @parentCategoryID = null, int? @categoryID = null, int? @groupProductID = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Product_By_GroupProductID_New";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CategoryID",@categoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupProductID",@groupProductID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GetOderProductNPP(this IDbConnection db, string @productId = null, string @network = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GetOderProductNPP";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"productId",@productId,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"network",@network,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Core_Store_By_id(this IDbConnection db, int? @storeID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Core_Store_By_id";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreID",@storeID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Category_By_ParentCategoryID_New(this IDbConnection db, int? @providerID = null, int? @parentCategoryID = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Category_By_ParentCategoryID_New";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_PromotionDiscountProduct_Network_Search(this IDbConnection db, string @networkCode = null, string @level = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_PromotionDiscountProduct_Network_Search";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Level",@level,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectAll_Order_Paging(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, int? @providerID = null, int? @storeID = null, int? @networkID = null, int? @pageIndex = null, int? @pageSize = null, int? @recordCount = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectAll_Order_Paging";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreID",@storeID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkID",@networkID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageIndex",@pageIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageSize",@pageSize,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RecordCount",@recordCount,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Core_CostBouns_Pagging(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, string @type = null, int? @status = null, string @provider = null, int? @pageIndex = null, int? @pageSize = null, int? @recordCount = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Core_CostBouns_Pagging";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Type",@type,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Provider",@provider,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageIndex",@pageIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageSize",@pageSize,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RecordCount",@recordCount,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_OrderDetail_By_Id(this IDbConnection db, int? @id = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_OrderDetail_By_Id";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Id",@id,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Deposit_SelectPaging(this IDbConnection db, string @networkCode = null, string @networkLevel = null, int? @pageIndex = null, int? @pageSize = null, int? @recordCount = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Deposit_SelectPaging";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"networkLevel",@networkLevel,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageIndex",@pageIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageSize",@pageSize,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RecordCount",@recordCount,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Core_OrderDetail_By_ID(this IDbConnection db, int? @orderID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Core_OrderDetail_By_ID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderID",@orderID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Core_OrderDetail_By_OrderID(this IDbConnection db, int? @orderID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Core_OrderDetail_By_OrderID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderID",@orderID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Deposit_By_DepositID_VNPOST(this IDbConnection db, int? @depositID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Deposit_By_DepositID_VNPOST";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DepositID",@depositID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_View_SaleBouns_By_SaleBounsID(this IDbConnection db, int? @saleBounsID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_View_SaleBouns_By_SaleBounsID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SaleBounsID",@saleBounsID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectAll_Provider(this IDbConnection db, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectAll_Provider";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_ParentCategory_By_ProviderID(this IDbConnection db, int? @providerID = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_ParentCategory_By_ProviderID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement GetProductBySearch(this IDbConnection db, int? @distributorsID = null, int? @providerID = null, int? @parentCategoryID = null, int? @categoryID = null, string @codeOrName = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "GetProductBySearch";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DistributorsID",@distributorsID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CategoryID",@categoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CodeOrName",@codeOrName,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Category_By_ParentCategoryID(this IDbConnection db, int? @parentCategoryID = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Category_By_ParentCategoryID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Deposit_GetnetWork(this IDbConnection db, string @networkCode = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Deposit_GetnetWork";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_CustomerDiscount_Pagging(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, int? @networkID = null, string @levelType = null, string @receivedLevel = null, int? @parentCategoryID = null, int? @productID = null, int? @status = null, int? @pageIndex = null, int? @pageSize = null, int? @recordCount = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_CustomerDiscount_Pagging";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkID",@networkID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"LevelType",@levelType,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ReceivedLevel",@receivedLevel,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageIndex",@pageIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageSize",@pageSize,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RecordCount",@recordCount,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ProductInventory(this IDbConnection db, int? @storeId = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ProductInventory";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"storeId",@storeId,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_GroupProduct_By_CategoryID(this IDbConnection db, int? @categoryID = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_GroupProduct_By_CategoryID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CategoryID",@categoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Deposit_GetVI21_By_NetworkCode(this IDbConnection db, string @networkCode = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Deposit_GetVI21_By_NetworkCode";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_CustomerDiscount_By_ID(this IDbConnection db, int? @iD = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_CustomerDiscount_By_ID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ID",@iD,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Core_OrderInputDetailEdit_By_OrderID(this IDbConnection db, int? @orderID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Core_OrderInputDetailEdit_By_OrderID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderID",@orderID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Product_By_GroupProductID(this IDbConnection db, int? @groupProductID = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Product_By_GroupProductID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupProductID",@groupProductID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectAll_ParentCategory(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectAll_ParentCategory";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_DiscountPurchases_Select_Product(this IDbConnection db, int? @providerID = null, int? @distributorsID = null, int? @parentCategoryID = null, int? @trademarkID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_DiscountPurchases_Select_Product";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DistributorsID",@distributorsID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"TrademarkID",@trademarkID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Unit_By_ProductID(this IDbConnection db, int? @productID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Unit_By_ProductID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectAll_Trademark(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectAll_Trademark";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ExportCoupon_Detail_Edit_By_ID(this IDbConnection db, int? @orderID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ExportCoupon_Detail_Edit_By_ID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderID",@orderID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Product_By_Trademark_ParentCategory(this IDbConnection db, int? @trademarkID = null, int? @parentCategoryID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Product_By_Trademark_ParentCategory";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"TrademarkID",@trademarkID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_DiscountPurchases_Select_Product_v2(this IDbConnection db, int? @providerID = null, int? @distributorsID = null, int? @parentCategoryID = null, int? @trademarkID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_DiscountPurchases_Select_Product_v2";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DistributorsID",@distributorsID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"TrademarkID",@trademarkID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_PromotionDiscountProduct_Check_Product(this IDbConnection db, int? @productID = null, int? @unitID = null, int? @startQuantity = null, int? @endQuantity = null, DateTime? @fromDate = null, int? @errorToBeReturned = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_PromotionDiscountProduct_Check_Product";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UnitID",@unitID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StartQuantity",@startQuantity,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"EndQuantity",@endQuantity,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ErrorToBeReturned",@errorToBeReturned,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GetProduct2(this IDbConnection db, string @productId = null, int? @storeCode = null, string @network = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GetProduct2";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"productId",@productId,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreCode",@storeCode,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"network",@network,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Core_CostBouns_Export(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, string @type = null, int? @status = null, string @provider = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Core_CostBouns_Export";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Type",@type,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Provider",@provider,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectStoreExport(this IDbConnection db, string @searchText = null, string @userName = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectStoreExport";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectStoreImport(this IDbConnection db, string @networkCode = null, string @searchText = null, string @userName = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectStoreImport";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Insert_SalePrice(this IDbConnection db, int? @productID = null, decimal? @price = null, decimal? @priceNoVat = null, decimal? @vat = null, int? @unitID = null, DateTime? @fromDate = null, DateTime? @toDate = null, string @userCreated = null, string @type = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Insert_SalePrice";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Price",@price,ParameterDirection.Input,DbType.Decimal));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PriceNoVat",@priceNoVat,ParameterDirection.Input,DbType.Decimal));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Vat",@vat,ParameterDirection.Input,DbType.Decimal));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UnitID",@unitID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserCreated",@userCreated,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Type",@type,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Store_By_NetworkCode(this IDbConnection db, string @networkCode = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Store_By_NetworkCode";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Product_By_StoreExport(this IDbConnection db, int? @storeID = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Product_By_StoreExport";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreID",@storeID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectAll_SalePrice_Paging(this IDbConnection db, DateTime? @fromDate = null, DateTime? @toDate = null, int? @productID = null, int? @groupProductID = null, int? @categoryID = null, int? @parentCategoryID = null, int? @providerID = null, int? @status = null, int? @pageIndex = null, int? @pageSize = null, int? @recordCount = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectAll_SalePrice_Paging";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupProductID",@groupProductID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CategoryID",@categoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentCategoryID",@parentCategoryID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProviderID",@providerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageIndex",@pageIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageSize",@pageSize,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RecordCount",@recordCount,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Order_By_Store_Product(this IDbConnection db, int? @productID = null, int? @storeID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Order_By_Store_Product";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreID",@storeID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Unit_By_Order(this IDbConnection db, string @orderCode = null, int? @storeID = null, int? @productID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Unit_By_Order";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderCode",@orderCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreID",@storeID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SaleProductBouns_Insert(this IDbConnection db, int? @productID = null, int? @unitID = null, decimal? @discount = null, DateTime? @fromDate = null, DateTime? @toDate = null, int? @status = null, int? @startQuantity = null, int? @endQuantity = null, string @userCreated = null, string @type = null, string @systemType = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SaleProductBouns_Insert";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UnitID",@unitID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Discount",@discount,ParameterDirection.Input,DbType.Decimal));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StartQuantity",@startQuantity,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"EndQuantity",@endQuantity,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserCreated",@userCreated,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Type",@type,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SystemType",@systemType,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Select_Quantity_BlockQuantity(this IDbConnection db, int? @productID = null, int? @detailType = null, int? @unitID = null, string @orderCode = null, int? @storeID = null, string @networkCode = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Select_Quantity_BlockQuantity";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DetailType",@detailType,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UnitID",@unitID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"OrderCode",@orderCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"StoreID",@storeID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectAll_SaleProductBouns_Paging(this IDbConnection db, int? @pageIndex = null, int? @pageSize = null, int? @recordCount = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectAll_SaleProductBouns_Paging";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageIndex",@pageIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageSize",@pageSize,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RecordCount",@recordCount,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Insert_Core_Limit(this IDbConnection db, int? @networkID = null, string @levelType = null, decimal? @maxAmount = null, int? @limit = null, DateTime? @fromDate = null, DateTime? @toDate = null, string @limitType = null, string @userCreated = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Insert_Core_Limit";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkID",@networkID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"LevelType",@levelType,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"MaxAmount",@maxAmount,ParameterDirection.Input,DbType.Decimal));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Limit",@limit,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"LimitType",@limitType,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserCreated",@userCreated,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectAll_Limit_Paging(this IDbConnection db, string @limitType = null, DateTime? @fromDate = null, DateTime? @toDate = null, string @parentNetworkCode = null, string @networkCode = null, string @levelType = null, int? @status = null, int? @pageIndex = null, int? @pageSize = null, int? @recordCount = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectAll_Limit_Paging";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"LimitType",@limitType,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentNetworkCode",@parentNetworkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"LevelType",@levelType,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageIndex",@pageIndex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageSize",@pageSize,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RecordCount",@recordCount,ParameterDirection.InputOutput,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Deposit_GetUserDeposit(this IDbConnection db, string @networkCode = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Deposit_GetUserDeposit";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_CostBouns_SelectQuantity(this IDbConnection db, int? @costBounsID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_CostBouns_SelectQuantity";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CostBounsID",@costBounsID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Deposit_GetCodeDeposit(this IDbConnection db, int? @customerID = null, string @networkCode = null, string @searchText = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Deposit_GetCodeDeposit";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CustomerID",@customerID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NetworkCode",@networkCode,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ExportCoupon_GetNetwork(this IDbConnection db, string @userName = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ExportCoupon_GetNetwork";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SalePrice_CheckExist(this IDbConnection db, int? @productID = null, int? @unitID = null, DateTime? @fromDate = null, DateTime? @toDate = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SalePrice_CheckExist";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProductID",@productID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UnitID",@unitID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FromDate",@fromDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ToDate",@toDate,ParameterDirection.Input,DbType.DateTime));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SearchAllProvider_Product(this IDbConnection db, string @searchText = null, int? @provider = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SearchAllProvider_Product";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SearchText",@searchText,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Provider",@provider,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SelectAll_Distributors(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SelectAll_Distributors";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

	}

	
}
 