


















 


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ConnectionString_OzeGeneral`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `server=210.211.126.238;UID=sa;PWD=sa123$%;database=OzeGeneral;Connect Timeout=30;Pooling=false;`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
using System;
using System.Data.Common;
using System.Data;
using System.Collections.Generic;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;

namespace StoredProcedures
{
	public static class SPList 
	{
		private static DbParameter CreateNewParameter(DbCommand dbCommand, string paramName, object paramValue, ParameterDirection paramDirection, DbType paramType)
		{
			DbParameter param = dbCommand.CreateParameter();
			param.Direction = paramDirection;
			param.DbType = paramType;
			param.ParameterName = paramName;
			param.Value = paramValue ?? DBNull.Value;
			return param;
		}

		public static OrmLiteSPStatement sp_Get_Category(this IDbConnection db, string @type = null, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Category";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Type",@type,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Customer_Booking(this IDbConnection db, string @hotelCode = null, string @bookingCode = null, int? @reservationType = null, int? @reservationStatus = null, int? @roomID = null, int? @roomType = null, string @arrive_Date = null, string @leave_Date = null, string @customerName = null, int? @pageNumber = null, int? @rowspPage = null, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Customer_Booking";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"HotelCode",@hotelCode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"BookingCode",@bookingCode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ReservationType",@reservationType,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ReservationStatus",@reservationStatus,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RoomID",@roomID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RoomType",@roomType,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Arrive_Date",@arrive_Date,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Leave_Date",@leave_Date,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CustomerName",@customerName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageNumber",@pageNumber,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RowspPage",@rowspPage,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GetModules(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GetModules";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Customer_Booking_Detail(this IDbConnection db, string @bookingCode = null, string @hotelCode = null, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Customer_Booking_Detail";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"BookingCode",@bookingCode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"HotelCode",@hotelCode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Menu_By_User(this IDbConnection db, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Menu_By_User";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Customer_Booking_dev(this IDbConnection db, string @bookingCode = null, int? @reservationType = null, int? @reservationStatus = null, int? @roomID = null, int? @roomType = null, string @arrive_Date = null, string @leave_Date = null, string @customerName = null, int? @pageNumber = null, int? @rowspPage = null, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Customer_Booking_dev";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"BookingCode",@bookingCode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ReservationType",@reservationType,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ReservationStatus",@reservationStatus,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RoomID",@roomID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RoomType",@roomType,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Arrive_Date",@arrive_Date,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Leave_Date",@leave_Date,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CustomerName",@customerName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageNumber",@pageNumber,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RowspPage",@rowspPage,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_List_Memus(this IDbConnection db, int? @parentID = null, int? @status = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_List_Memus";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentID",@parentID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Reservation_Type(this IDbConnection db, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Reservation_Type";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Hotels(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Hotels";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Room(this IDbConnection db, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Room";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_GroupsMenuRel(this IDbConnection db, int? @groupID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_GroupsMenuRel";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupID",@groupID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Room_Level(this IDbConnection db, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Room_Level";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Groups_ByID(this IDbConnection db, int? @iD = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Groups_ByID";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ID",@iD,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Room_Status(this IDbConnection db, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Room_Status";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Groups(this IDbConnection db, string @sysHotelCode = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Groups";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SysHotelCode",@sysHotelCode,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_Room_Type(this IDbConnection db, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_Room_Type";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_All_Menus_list(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_All_Menus_list";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_PhuTroi_Create(this IDbConnection db, string @name = null, string @reservationType = null, string @codePhuTroi = null, int? @totalHours = null, int? @numberPeople = null, double? @price = null, string @roomTypeCode = null, int? @retCode = null, string @retMess = null, string @retPhuTroiCode = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_PhuTroi_Create";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Name",@name,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ReservationType",@reservationType,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CodePhuTroi",@codePhuTroi,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"TotalHours",@totalHours,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"NumberPeople",@numberPeople,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Price",@price,ParameterDirection.Input,DbType.Double));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RoomTypeCode",@roomTypeCode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetCode",@retCode,ParameterDirection.InputOutput,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetMess",@retMess,ParameterDirection.InputOutput,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetPhuTroiCode",@retPhuTroiCode,ParameterDirection.InputOutput,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_All_Menus(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_All_Menus";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_ReservationRoom_Create(this IDbConnection db, string @activity = null, string @fullName = null, int? @sex = null, string @dOB = null, string @identityNumber = null, int? @citizenshipCode = null, string @company = null, string @address = null, string @email = null, string @mobile = null, int? @createby = null, string @reservationCode = null, int? @room_Level_ID = null, int? @reservationType = null, int? @payment_Type_ID = null, int? @roomTypeID = null, double? @deposit = null, double? @price = null, string @arrivalDate = null, string @leave_Date = null, int? @number_People = null, double? @discount = null, string @hotelCode = null, string @note = null, int? @retCode = null, string @retMesg = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_ReservationRoom_Create";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Activity",@activity,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FullName",@fullName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Sex",@sex,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DOB",@dOB,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"IdentityNumber",@identityNumber,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CitizenshipCode",@citizenshipCode,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Company",@company,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Address",@address,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Email",@email,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Mobile",@mobile,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Createby",@createby,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ReservationCode",@reservationCode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Room_Level_ID",@room_Level_ID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ReservationType",@reservationType,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Payment_Type_ID",@payment_Type_ID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RoomTypeID",@roomTypeID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Deposit",@deposit,ParameterDirection.Input,DbType.Double));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Price",@price,ParameterDirection.Input,DbType.Double));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ArrivalDate",@arrivalDate,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Leave_Date",@leave_Date,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Number_People",@number_People,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Discount",@discount,ParameterDirection.Input,DbType.Double));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"HotelCode",@hotelCode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Note",@note,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetCode",@retCode,ParameterDirection.InputOutput,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetMesg",@retMesg,ParameterDirection.InputOutput,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Get_AccessRight(this IDbConnection db, int? @groupID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Get_AccessRight";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupID",@groupID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Delete_Groups(this IDbConnection db, int? @groupID = null, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Delete_Groups";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupID",@groupID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Delete_GroupMenuRel(this IDbConnection db, int? @iD = null, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Delete_GroupMenuRel";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ID",@iD,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Create_GroupsMenuRel(this IDbConnection db, int? @groupID = null, int? @menuID = null, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Create_GroupsMenuRel";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupID",@groupID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"MenuID",@menuID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_RoomType_Create(this IDbConnection db, string @name = null, string @code = null, int? @douldBed = null, int? @singBed = null, int? @retCode = null, string @retMess = null, string @retRoomTypeCode = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_RoomType_Create";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Name",@name,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Code",@code,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DouldBed",@douldBed,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SingBed",@singBed,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetCode",@retCode,ParameterDirection.InputOutput,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetMess",@retMess,ParameterDirection.InputOutput,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetRoomTypeCode",@retRoomTypeCode,ParameterDirection.InputOutput,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Create_Groups(this IDbConnection db, string @groupName = null, int? @groupType = null, string @description = null, int? @sysHotelID = null, int? @status = null, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Create_Groups";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupName",@groupName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupType",@groupType,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Description",@description,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SysHotelID",@sysHotelID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Account_UpdateSysUser(this IDbConnection db, int? @iD = null, string @password = null, string @identityNumber = null, string @fullName = null, string @address = null, string @mobile = null, string @email = null, int? @department = null, int? @parentID = null, int? @sysHotelID = null, int? @status = null, int? @isActive = null, int? @modifyby = null, DateTime? @modifyDate = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Account_UpdateSysUser";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ID",@iD,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Password",@password,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"IdentityNumber",@identityNumber,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FullName",@fullName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Address",@address,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Mobile",@mobile,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Email",@email,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Department",@department,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentID",@parentID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SysHotelID",@sysHotelID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"IsActive",@isActive,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Modifyby",@modifyby,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ModifyDate",@modifyDate,ParameterDirection.Input,DbType.DateTime));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Account_Update_PW(this IDbConnection db, string @userName = null, string @email = null, string @password = null, int? @firstLogin = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Account_Update_PW";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Email",@email,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Password",@password,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FirstLogin",@firstLogin,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Account_Register(this IDbConnection db, string @userName = null, string @email = null, string @password = null, string @identityNumber = null, string @fullName = null, string @address = null, string @mobile = null, int? @department = null, int? @parentID = null, int? @sysHotelID = null, int? @status = null, int? @isActive = null, int? @createby = null, DateTime? @createDate = null, int? @modifyby = null, DateTime? @modifyDate = null, int? @retCode = null, string @retMesg = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Account_Register";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Email",@email,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Password",@password,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"IdentityNumber",@identityNumber,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FullName",@fullName,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Address",@address,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Mobile",@mobile,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Department",@department,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentID",@parentID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SysHotelID",@sysHotelID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"IsActive",@isActive,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Createby",@createby,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CreateDate",@createDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Modifyby",@modifyby,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ModifyDate",@modifyDate,ParameterDirection.Input,DbType.DateTime));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetCode",@retCode,ParameterDirection.InputOutput,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetMesg",@retMesg,ParameterDirection.InputOutput,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Account_Login(this IDbConnection db, string @userName = null, string @password = null, int? @retCode = null, string @retMesg = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Account_Login";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Password",@password,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetCode",@retCode,ParameterDirection.InputOutput,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetMesg",@retMesg,ParameterDirection.InputOutput,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Account_GetInfomation(this IDbConnection db, int? @userID = null, string @userName = null, string @email = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Account_GetInfomation";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Email",@email,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Account_GetGroupsByUser(this IDbConnection db, string @userName = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Account_GetGroupsByUser";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Account_DetailSysUser(this IDbConnection db, int? @iD = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Account_DetailSysUser";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ID",@iD,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Account_DeleteSysUser(this IDbConnection db, int? @iD = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Account_DeleteSysUser";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ID",@iD,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_AccessRight_Create(this IDbConnection db, int? @groupID = null, int? @modelID = null, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_AccessRight_Create";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupID",@groupID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ModelID",@modelID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Update_AccessRight(this IDbConnection db, int? @groupID = null, string @ruleID = null, string @read = null, string @write = null, string @create = null, string @delete = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Update_AccessRight";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupID",@groupID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RuleID",@ruleID,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Read",@read,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Write",@write,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Create",@create,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Delete",@delete,ParameterDirection.Input,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Territories(this IDbConnection db, string @activity = null, string @provincesName = null, string @districtName = null, string @wardsName = null, string @provincesId = null, string @districtId = null, string @wardsId = null, int? @retCode = null, string @retMesg = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Territories";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Activity",@activity,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProvincesName",@provincesName,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DistrictName",@districtName,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"WardsName",@wardsName,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ProvincesId",@provincesId,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"DistrictId",@districtId,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"WardsId",@wardsId,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetCode",@retCode,ParameterDirection.InputOutput,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetMesg",@retMesg,ParameterDirection.InputOutput,DbType.AnsiString));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SysUsers_Insert(this IDbConnection db, string @userName = null, string @password = null, string @identityNumber = null, string @fullName = null, string @address = null, string @email = null, string @mobile = null, int? @firstLogin = null, int? @department = null, int? @parentID = null, int? @sysHotelID = null, int? @status = null, int? @isActive = null, int? @createby = null, DateTime? @createDate = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SysUsers_Insert";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserName",@userName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Password",@password,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"IdentityNumber",@identityNumber,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FullName",@fullName,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Address",@address,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Email",@email,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Mobile",@mobile,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"FirstLogin",@firstLogin,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Department",@department,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ParentID",@parentID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"SysHotelID",@sysHotelID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"IsActive",@isActive,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Createby",@createby,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"CreateDate",@createDate,ParameterDirection.Input,DbType.DateTime));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SysUser_GetInforUser(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SysUser_GetInforUser";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SysUser_GetAllUser(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SysUser_GetAllUser";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_SysAccessRights_Delete(this IDbConnection db, int? @groupID = null, int? @modelID = null, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_SysAccessRights_Delete";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"GroupID",@groupID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ModelID",@modelID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_right_permission(this IDbConnection db, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_right_permission";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Menu_Get_By_User(this IDbConnection db, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Menu_Get_By_User";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Hotels_Update(this IDbConnection db, string @code = null, string @name = null, string @address = null, string @phone = null, string @mobile = null, string @email = null, string @website = null, string @logoUrl = null, int? @roomCount = null, string @description = null, int? @status = null, int? @modifyby = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Hotels_Update";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Code",@code,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Name",@name,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Address",@address,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Phone",@phone,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Mobile",@mobile,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Email",@email,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Website",@website,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"LogoUrl",@logoUrl,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RoomCount",@roomCount,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Description",@description,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Modifyby",@modifyby,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Hotels_Insert(this IDbConnection db, string @name = null, string @address = null, string @phone = null, string @mobile = null, string @email = null, string @website = null, string @logoUrl = null, int? @roomCount = null, string @description = null, int? @status = null, int? @createby = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Hotels_Insert";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Name",@name,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Address",@address,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Phone",@phone,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Mobile",@mobile,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Email",@email,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Website",@website,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"LogoUrl",@logoUrl,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RoomCount",@roomCount,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Description",@description,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Status",@status,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Createby",@createby,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Hotels_GetAll(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Hotels_GetAll";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Hotels_Get_List(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Hotels_Get_List";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Hotels_Delete(this IDbConnection db, string @code = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Hotels_Delete";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Code",@code,ParameterDirection.Input,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GroupType_GetAll(this IDbConnection db, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GroupType_GetAll";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_right_permission_all(this IDbConnection db, int? @userID = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_right_permission_all";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"UserID",@userID,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Account_UserUpdate(this IDbConnection db, int? @iD = null, string @address = null, string @mobile = null, string @email = null, int? @modifyby = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Account_UserUpdate";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ID",@iD,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Address",@address,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Mobile",@mobile,ParameterDirection.Input,DbType.AnsiString));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Email",@email,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Modifyby",@modifyby,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Room_GetAllRoom(this IDbConnection db)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Room_GetAllRoom";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Room_Update_RoomName(this IDbConnection db, int? @iD = null, string @name = null, int? @retCode = null, string @retMesg = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Room_Update_RoomName";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ID",@iD,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Name",@name,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetCode",@retCode,ParameterDirection.InputOutput,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetMesg",@retMesg,ParameterDirection.InputOutput,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Room_Delete_Room(this IDbConnection db, int? @iD = null, int? @retCode = null, string @retMesg = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Room_Delete_Room";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ID",@iD,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetCode",@retCode,ParameterDirection.InputOutput,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RetMesg",@retMesg,ParameterDirection.InputOutput,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_Create_Rooms(this IDbConnection db, string @name = null, string @floor = null, string @postion = null, int? @roomType_ID = null, int? @roomLevel_ID = null, int? @building_ID = null, string @temp = null, int? @active = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_Create_Rooms";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Name",@name,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Floor",@floor,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Postion",@postion,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RoomType_ID",@roomType_ID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RoomLevel_ID",@roomLevel_ID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Building_ID",@building_ID,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Temp",@temp,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Active",@active,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GetGroup_PagingRows(this IDbConnection db, int? @pageNumber = null, int? @rowspPage = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GetGroup_PagingRows";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"PageNumber",@pageNumber,ParameterDirection.Input,DbType.Int32));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"RowspPage",@rowspPage,ParameterDirection.Input,DbType.Int32));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

		public static OrmLiteSPStatement sp_GenCode(this IDbConnection db, string @activity = null, string @hotelCode = null, string @returnCode = null)
		{
			var dbCmd = (DbCommand)OrmLiteConfig.ExecFilter.CreateCommand(db).ToDbCommand();
			dbCmd.CommandText = "sp_GenCode";
			dbCmd.CommandType = CommandType.StoredProcedure;
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"Activity",@activity,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"HotelCode",@hotelCode,ParameterDirection.Input,DbType.String));
			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"ReturnCode",@returnCode,ParameterDirection.InputOutput,DbType.String));
 			dbCmd.Parameters.Add(CreateNewParameter(dbCmd,"__ReturnValue",0,ParameterDirection.ReturnValue,DbType.Int32));
			return new OrmLiteSPStatement(db, dbCmd);
		}

	}

	
}
 