


















 


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ConnectionString_OzeGeneral`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `server=210.211.126.238;UID=sa;PWD=210sa123!;database=OzeShop;Connect Timeout=30;Pooling=false;`
//     Schema:                 ``
//     Include Views:          `True`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace oze.data
{
	[Alias("Area_Province_VNPOST")]
    public partial class Area_Province_VNPOST : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? areaid { get; set; }
        public int? provinceid { get; set; }
        public int? lang { get; set; }
    }

	[Alias("AreaVNPOST")]
    public partial class AreaVNPOST : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public int? stt { get; set; }
        public int? lang { get; set; }
    }

	[Alias("FeeVNPOST")]
    public partial class FeeVNPOST : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? typeFee { get; set; }
        public decimal? localFee { get; set; }
        public decimal? nearFee { get; set; }
        public decimal? farFee { get; set; }
        public decimal? fromWeight { get; set; }
        public decimal? toWeight { get; set; }
        public int? lang { get; set; }
    }

	[Alias("tbl_Album_Image_Rel")]
    public partial class tbl_Album_Image_Rel : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? albumid { get; set; }
        public int? fileid { get; set; }
        public int? datecreated { get; set; }
    }

	[Alias("tbl_Albums")]
    public partial class tbl_Album : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public string title { get; set; }
        public string desc { get; set; }
        public DateTime? datecreated { get; set; }
        public int? creatorid { get; set; }
    }

	[Alias("tbl_Country")]
    public partial class tbl_Country 
    {
        [AutoIncrement]
        public int id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Nationality { get; set; }
    }

	[Alias("tbl_District")]
    public partial class tbl_District : IHasId<string> 
    {
        [Alias("ID")]
        [Required]
        public string Id { get; set; }
        [Required]
        public string NameVN { get; set; }
        public string NameEN { get; set; }
        public int? Level { get; set; }
        [Required]
        public string Province_id { get; set; }
    }

	[Alias("tbl_DistrictLevel")]
    public partial class tbl_DistrictLevel : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string NameVN { get; set; }
        public string NameEN { get; set; }
        [Required]
        public int Level { get; set; }
    }

	[Alias("tbl_Files")]
    public partial class tbl_File : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public string title { get; set; }
        public string path { get; set; }
        public string paththumb { get; set; }
        public int? typeFile { get; set; }
        public DateTime? datecreated { get; set; }
        public int? userid { get; set; }
    }

	[Alias("tbl_GroupType")]
    public partial class tbl_GroupType : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string NameVN { get; set; }
        public string NameEN { get; set; }
        [Required]
        public int Order { get; set; }
        public string code { get; set; }
    }

	[Alias("tbl_HotelAlbums")]
    public partial class tbl_HotelAlbum : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        public int Status { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
    }

	[Alias("tbl_HotelAreaInfo")]
    public partial class tbl_HotelAreaInfo : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        [Required]
        public string Name { get; set; }
        public int? ProvinceID { get; set; }
        public string Address { get; set; }
        public double? Longitude { get; set; }
        public double? Latiude { get; set; }
        public double? Distance { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        [Required]
        public int Status { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
    }

	[Alias("tbl_Hotels")]
    public partial class tbl_Hotel : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        public string Code { get; set; }
        [Required]
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string LogoUrl { get; set; }
        [Required]
        public int RoomCount { get; set; }
        public string Description { get; set; }
        [Required]
        public int Status { get; set; }
        public string HGCode { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
    }

	[Alias("tbl_HotelsConfig")]
    public partial class tbl_HotelsConfig : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public double? startCheckout { get; set; }
        public double? startCheckin { get; set; }
        public double? startNight1 { get; set; }
        public double? startNight2 { get; set; }
        public int? SysHotelID { get; set; }
        public int? startRoundMain { get; set; }
        public int? startRoundExatra { get; set; }
        public double? startCheckoutNight { get; set; }
    }

	[Alias("tbl_HotelsGroup")]
    public partial class tbl_HotelsGroup : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string Code { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public int? Status { get; set; }
        public DateTime? CreateDate { get; set; }
    }

	[Alias("tbl_Payment")]
    public partial class tbl_Payment : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? Payment_Type_ID { get; set; }
        public string CardNumber { get; set; }
        public string Bank_Acc { get; set; }
        public string Bank_Name { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? CreateBy { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? ModifyBy { get; set; }
        [Required]
        public int ResevationRoom_Code { get; set; }
        public string Desc { get; set; }
        public int? Bill_ID { get; set; }
        public double? TotalAmount { get; set; }
    }

	[Alias("tbl_Payment_Type")]
    public partial class tbl_Payment_Type : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        public string Name { get; set; }
        public int? Status { get; set; }
    }

	[Alias("tbl_ProductGroup")]
    public partial class tbl_ProductGroup : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        public int Status { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? SysHotelID { get; set; }
    }

	[Alias("tbl_Products")]
    public partial class tbl_Product : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        [Required]
        public int SupplierID { get; set; }
        public int? ProductCateID { get; set; }
        public int? UnitID { get; set; }
        public string Name { get; set; }
        [Required]
        public double PriceOrder { get; set; }
        [Required]
        public double SalePrice { get; set; }
        public DateTime? DateOrder { get; set; }
        public string PictureUrl { get; set; }
        public string Description { get; set; }
        [Required]
        public int Status { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? ProductGroupID { get; set; }
        public int? QuotaMinimize { get; set; }
        public string Code { get; set; }
        public int? vendorid { get; set; }
    }

	[Alias("tbl_Products_Image_Rel")]
    public partial class tbl_Products_Image_Rel : IHasId<int> 
    {
        [Alias("id")]
        [Required]
        public int Id { get; set; }
        public int? productid { get; set; }
        public int? fileid { get; set; }
        public DateTime? datecreated { get; set; }
        [AutoIncrement]
        public int userid { get; set; }
    }

	[Alias("tbl_Products_Price_Log")]
    public partial class tbl_Products_Price_Log : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public int ProductID { get; set; }
        [Required]
        public double SalePrice { get; set; }
        public int? UserID { get; set; }
        public DateTime? DateHis { get; set; }
    }

	[Alias("tbl_Products_Unit_Rel")]
    public partial class tbl_Products_Unit_Rel : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? productid { get; set; }
        public int? unitid { get; set; }
        public int? unitidmin { get; set; }
        public int? quantityMin { get; set; }
        public int? datecreated { get; set; }
        public bool? isunitmin { get; set; }
    }

	[Alias("tbl_Promotion")]
    public partial class tbl_Promotion : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public string title { get; set; }
        public DateTime? dateFrom { get; set; }
        public DateTime? dateTo { get; set; }
        public string desc { get; set; }
        public bool? isactive { get; set; }
        public DateTime? datecreated { get; set; }
        public int? vendorid { get; set; }
        public int? creatorid { get; set; }
    }

	[Alias("tbl_Promotion_ProductsPrice_Rel")]
    public partial class tbl_Promotion_ProductsPrice_Rel : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? productid { get; set; }
        public int? unitid { get; set; }
        public double? priceSale { get; set; }
        public double? pricePromotion { get; set; }
        public int? typePrice { get; set; }
        public int? quantityFrom { get; set; }
        public int? quantityTo { get; set; }
        public DateTime? datecreated { get; set; }
    }

	[Alias("tbl_Provinces")]
    public partial class tbl_Province : IHasId<string> 
    {
        [Alias("ID")]
        [Required]
        public string Id { get; set; }
        [Required]
        public string NameVN { get; set; }
        public string NamEN { get; set; }
        [Required]
        public int Level { get; set; }
    }

	[Alias("tbl_ProvincesLevel")]
    public partial class tbl_ProvincesLevel : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string NameVN { get; set; }
        public string NameEN { get; set; }
        public int? Level { get; set; }
    }

	[Alias("tbl_Purchase_Comment_Rel")]
    public partial class tbl_Purchase_Comment_Rel : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public string note { get; set; }
        public int? purchaseid { get; set; }
        public DateTime? datecreated { get; set; }
        public int? syshotelid { get; set; }
        public int? vendorid { get; set; }
        public int? userid { get; set; }
    }

	[Alias("tbl_PurchaseOrder")]
    public partial class tbl_PurchaseOrder : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? SysHotelID { get; set; }
        public int? VendorID { get; set; }
        public string OrderCode { get; set; }
        public string SupplierCode { get; set; }
        public double? AmountNoTax { get; set; }
        public double? Tax { get; set; }
        public double? TotalAmount { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DatePayment { get; set; }
        public DateTime? InputDate { get; set; }
        public int? PaymentTypeID { get; set; }
        public int? Status { get; set; }
        public int? TypeOrder { get; set; }
        public int? CreatorID { get; set; }
        public string Code { get; set; }
        public int? TypeOrderProcessing { get; set; }
    }

	[Alias("tbl_PurchaseOrderDetail")]
    public partial class tbl_PurchaseOrderDetail : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? SysHotelID { get; set; }
        public int? PurchaseID { get; set; }
        public string productName { get; set; }
        public string catalogName { get; set; }
        public int? productid { get; set; }
        public int? catalogid { get; set; }
        public int? quantity { get; set; }
        public double? Price { get; set; }
        public double? AmountNoTax { get; set; }
        public double? Tax { get; set; }
        public double? TotalAmount { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DatePayment { get; set; }
        public int? PaymentTypeID { get; set; }
        public int? TypeOrder { get; set; }
        public int? CreatorID { get; set; }
        public int? StoreID { get; set; }
        public DateTime? ManufactureDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public int? PurchaseMainId { get; set; }
        public int? quantityInput { get; set; }
        public double? PriceOrigin { get; set; }
        public double? PriceShipping { get; set; }
        public int? VendorID { get; set; }
    }

	[Alias("tbl_Reservation_Type")]
    public partial class tbl_Reservation_Type : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        public string Name { get; set; }
        public int? Position { get; set; }
    }

	[Alias("tbl_Room_Status")]
    public partial class tbl_Room_Status : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
    }

	[Alias("tbl_SaleOrder")]
    public partial class tbl_SaleOrder : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? SysHotelID { get; set; }
        public int? CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public double? AmountNoTax { get; set; }
        public double? Tax { get; set; }
        public double? TotalAmount { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DatePayment { get; set; }
        public int? PaymentTypeID { get; set; }
        public int? TypeOrder { get; set; }
        public int? CreatorID { get; set; }
        public int? CheckInID { get; set; }
        public double? Deduction { get; set; }
        public double? Discount { get; set; }
        public double? Deposit { get; set; }
    }

	[Alias("tbl_SaleOrderDetail")]
    public partial class tbl_SaleOrderDetail : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? SysHotelID { get; set; }
        public int? OrderID { get; set; }
        public string item { get; set; }
        public string catalogitem { get; set; }
        public int? itemid { get; set; }
        public int? catalogitemid { get; set; }
        public int? quantity { get; set; }
        public int? Price { get; set; }
        public double? AmountNoTax { get; set; }
        public double? Tax { get; set; }
        public double? TotalAmount { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DatePayment { get; set; }
        public int? PaymentTypeID { get; set; }
        public int? TypeOrder { get; set; }
        public int? CreatorID { get; set; }
        public int? StoreID { get; set; }
        public string descitem { get; set; }
    }

	[Alias("tbl_Shipper")]
    public partial class tbl_Shipper : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string Code { get; set; }
        [Required]
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact_Person_Name { get; set; }
        public string Contact_Person_Phone { get; set; }
        public string Contact_Person_Mobile { get; set; }
        public string Contact_Person_Email { get; set; }
        public string Email { get; set; }
        public string TaxCode { get; set; }
        [Required]
        public int Status { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? SysHotelID { get; set; }
    }

	[Alias("tbl_Store")]
    public partial class tbl_Store : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public string title { get; set; }
        public int? typeStore { get; set; }
        public DateTime? datecreated { get; set; }
        public int? roomid { get; set; }
        public string roomcode { get; set; }
        public int? creatorid { get; set; }
        public int? SysHotelID { get; set; }
        public int? minQuality { get; set; }
        public int? vendorid { get; set; }
    }

	[Alias("tbl_StoreProduct")]
    public partial class tbl_StoreProduct : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? productid { get; set; }
        public int? storeid { get; set; }
        public int? SysHotelID { get; set; }
        public DateTime? datecreated { get; set; }
        public int? quantity { get; set; }
        public string sku { get; set; }
        public string ordercodeRef { get; set; }
        public int? unitid { get; set; }
        public int? typeImportExport { get; set; }
        public int? fromstoreid { get; set; }
        public int? quantityOrder { get; set; }
        public double? priceOrder { get; set; }
    }

	[Alias("tbl_StoreProduct_Config")]
    public partial class tbl_StoreProduct_Config : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? productid { get; set; }
        public int? storeid { get; set; }
        public int? SysHotelID { get; set; }
        public DateTime? datecreated { get; set; }
        public int? minimize { get; set; }
        public string sku { get; set; }
        public string ordercodeRef { get; set; }
        public int? unitid { get; set; }
    }

	[Alias("tbl_StoreProductLog")]
    public partial class tbl_StoreProductLog : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? storeproductid { get; set; }
        public int? productid { get; set; }
        public int? storeid { get; set; }
        public int? SysHotelID { get; set; }
        public DateTime? datecreated { get; set; }
        public int? quantity { get; set; }
        public string sku { get; set; }
        public string ordercodeRef { get; set; }
        public int? unitid { get; set; }
        public int? typeImportExport { get; set; }
        public int? fromstoreid { get; set; }
        public int? quantityOrder { get; set; }
        public double? priceOrder { get; set; }
    }

	[Alias("tbl_Supplier")]
    public partial class tbl_Supplier : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string Code { get; set; }
        [Required]
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact_Person_Name { get; set; }
        public string Contact_Person_Phone { get; set; }
        public string Contact_Person_Mobile { get; set; }
        public string Contact_Person_Email { get; set; }
        public string Email { get; set; }
        public string TaxCode { get; set; }
        [Required]
        public int Status { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? SysHotelID { get; set; }
    }

	[Alias("tbl_SysAccessRights")]
    public partial class tbl_SysAccessRight 
    {
        [AutoIncrement]
        public int RuleID { get; set; }
        [Required]
        public int GroupID { get; set; }
        [Required]
        public int ModelID { get; set; }
        public bool? Read { get; set; }
        public bool? Write { get; set; }
        public bool? Create { get; set; }
        [Alias("Delete")]
        public bool? _Delete { get; set; }
    }

	[Alias("tbl_SysAlbumPicture_Rel")]
    public partial class tbl_SysAlbumPicture_Rel : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public int AlbumID { get; set; }
        [Required]
        public int PictureID { get; set; }
        [Required]
        public int Order { get; set; }
    }

	[Alias("tbl_SysGroupMenu_Rel")]
    public partial class tbl_SysGroupMenu_Rel 
    {
        [AutoIncrement]
        public int ID { get; set; }
        [Required]
        public int SysMenuID { get; set; }
        [Required]
        public int SysGroupID { get; set; }
    }

	[Alias("tbl_SysGroups")]
    public partial class tbl_SysGroup : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string GroupName { get; set; }
        public int? GroupType { get; set; }
        public string Description { get; set; }
        [Required]
        public string SysHotelCode { get; set; }
        [Required]
        public int Status { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
    }

	[Alias("tbl_SysGroupUser_Rel")]
    public partial class tbl_SysGroupUser_Rel 
    {
        [Required]
        public int SysUserID { get; set; }
        [Required]
        public int SysGroupID { get; set; }
    }

	[Alias("tbl_SysUser_Hotel_GroupType")]
    public partial class tbl_SysUser_Hotel_GroupType : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? userid { get; set; }
        public int? groupid { get; set; }
        public DateTime? datecreated { get; set; }
        public int? hotelid { get; set; }
    }

	[Alias("tbl_SysUsers")]
    public partial class tbl_SysUser : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string IdentityNumber { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public int? Department { get; set; }
        [Required]
        public int ParentID { get; set; }
        public int? SysHotelID { get; set; }
        [Required]
        public int Status { get; set; }
        [Required]
        public int IsActive { get; set; }
        [Required]
        public int FirstLogin { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? isSP { get; set; }
        public string token { get; set; }
        public DateTime? tokenDateExpired { get; set; }
    }

	[Alias("tbl_SysUsers_GroupType_Hotel")]
    public partial class tbl_SysUsers_GroupType_Hotel : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? userid { get; set; }
        public int? grouptypeid { get; set; }
        public int? hotelid { get; set; }
    }

	[Alias("tbl_SysUserTypes")]
    public partial class tbl_SysUserType : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string TypeName { get; set; }
        public string TypeDesc { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        [Required]
        public int Status { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
    }

	[Alias("tbl_TransferOrder")]
    public partial class tbl_TransferOrder : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? SysHotelID { get; set; }
        public int? SupplierID { get; set; }
        public string OrderCode { get; set; }
        public string SupplierCode { get; set; }
        public double? AmountNoTax { get; set; }
        public double? Tax { get; set; }
        public double? TotalAmount { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DatePayment { get; set; }
        public DateTime? InputDate { get; set; }
        public int? PaymentTypeID { get; set; }
        public int? Status { get; set; }
        public int? TypeOrder { get; set; }
        public int? CreatorID { get; set; }
    }

	[Alias("tbl_TransferOrderDetail")]
    public partial class tbl_TransferOrderDetail : IHasId<int> 
    {
        [Alias("id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int? SysHotelID { get; set; }
        public int? TransferID { get; set; }
        public string item { get; set; }
        public string catalogitem { get; set; }
        public int? itemid { get; set; }
        public int? catalogitemid { get; set; }
        public int? quantity { get; set; }
        public int? Price { get; set; }
        public double? AmountNoTax { get; set; }
        public double? Tax { get; set; }
        public double? TotalAmount { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DatePayment { get; set; }
        public int? PaymentTypeID { get; set; }
        public int? TypeOrder { get; set; }
        public int? CreatorID { get; set; }
        public int? StoreID { get; set; }
        public int? FromStoreId { get; set; }
        public DateTime? ManufactureDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
    }

	[Alias("tbl_Units")]
    public partial class tbl_Unit : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        [Required]
        public int Status { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? SysHotelID { get; set; }
        public int? vendorid { get; set; }
        public bool? isunitmin { get; set; }
    }

	[Alias("tbl_Wards")]
    public partial class tbl_Ward : IHasId<string> 
    {
        [Alias("ID")]
        [Required]
        public string Id { get; set; }
        [Required]
        public string NameVN { get; set; }
        public string NameEN { get; set; }
        public int? Level { get; set; }
        [Required]
        public string Dist_id { get; set; }
        [Required]
        public string Province_id { get; set; }
    }

	[Alias("tbl_WardsLevel")]
    public partial class tbl_WardsLevel : IHasId<int> 
    {
        [Alias("ID")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string NameVN { get; set; }
        public string NameEN { get; set; }
        [Required]
        public int Level { get; set; }
    }

	[Alias("view_DetailProduct")]
    public partial class view_DetailProduct 
    {
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? DateOrder { get; set; }
        [Required]
        public int ID { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string Name { get; set; }
        public string PictureUrl { get; set; }
        public int? ProductCateID { get; set; }
        public int? UnitID { get; set; }
        public int? ProductGroupID { get; set; }
        [Required]
        public double SalePrice { get; set; }
        [Required]
        public double PriceOrder { get; set; }
        [Required]
        public int SupplierID { get; set; }
        public string Description { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        [Required]
        public int Status { get; set; }
        public int? QuotaMinimize { get; set; }
        public string Code { get; set; }
        public string ProductGroupName { get; set; }
        public string SupplierName { get; set; }
        public string UnitName { get; set; }
    }

	[Alias("view_DetailUser")]
    public partial class view_DetailUser 
    {
        [Required]
        public int ID { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string IdentityNumber { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public int? Department { get; set; }
        [Required]
        public int ParentID { get; set; }
        public int? SysHotelID { get; set; }
        [Required]
        public int Status { get; set; }
        [Required]
        public int IsActive { get; set; }
        [Required]
        public int FirstLogin { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? isSP { get; set; }
        public string HotelName { get; set; }
        public string GroupName { get; set; }
        public int? grouptypeid { get; set; }
    }

	[Alias("view_GetRoomForRoomType")]
    public partial class view_GetRoomForRoomType 
    {
        [Required]
        public int ID { get; set; }
        public string Name { get; set; }
        public string Floor { get; set; }
        public string Postion { get; set; }
        public int? RoomType_ID { get; set; }
        public int? RoomLevel_ID { get; set; }
        public int? Building_ID { get; set; }
        public string Temp { get; set; }
        public int? Active { get; set; }
        public int? SysHotelID { get; set; }
        public int? status { get; set; }
        public DateTime? datePlanFrom { get; set; }
        public DateTime? datePlanTo { get; set; }
        public int? status1 { get; set; }
        public string Code { get; set; }
        public string RoomType_Name { get; set; }
        public int? SingBed { get; set; }
        public int? DouldBed { get; set; }
        public string Note { get; set; }
        public int? UserLimit { get; set; }
    }

	[Alias("Vw_CustomerArrive_Room")]
    public partial class Vw_CustomerArrive_Room 
    {
        [Required]
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public DateTime? DOB { get; set; }
        public string Company { get; set; }
        public int? CountryId { get; set; }
        [Required]
        public int CustomerTypeID { get; set; }
        public int? Sex { get; set; }
        public int? TeamMergeSTT { get; set; }
        public int? TeamSTT { get; set; }
        [Required]
        public int roomid { get; set; }
        public int? Room_Type_ID { get; set; }
        public int? CheckInID { get; set; }
        public string IdentifyNumber { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        public DateTime? Arrive_Date { get; set; }
        public DateTime? Leave_Date { get; set; }
        public DateTime? Early_Arrival_Time { get; set; }
        public DateTime? CreateDate { get; set; }
        [Required]
        public string BookingCode { get; set; }
        [Required]
        public string HotelCode { get; set; }
        public string RoomName { get; set; }
        public string RoomTypeName { get; set; }
        public string Note { get; set; }
    }

	[Alias("Vw_HotelsConfig")]
    public partial class Vw_HotelsConfig 
    {
        public int? Id { get; set; }
        public double? startCheckin { get; set; }
        public double? startCheckout { get; set; }
        public double? startNight1 { get; set; }
        public double? startNight2 { get; set; }
        public int? startRoundMain { get; set; }
        public int? startRoundExatra { get; set; }
        public double? startCheckoutNight { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        [Required]
        public string Name { get; set; }
    }

	[Alias("Vw_InforCustomer")]
    public partial class Vw_InforCustomer 
    {
        [Required]
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public DateTime? DOB { get; set; }
        public string Company { get; set; }
        public int? CountryId { get; set; }
        [Required]
        public int CustomerTypeID { get; set; }
        public int? Sex { get; set; }
        public int? TeamMergeSTT { get; set; }
        public int? TeamSTT { get; set; }
        public string IdentifyNumber { get; set; }
        public string RoomName { get; set; }
        public string BookingCode { get; set; }
        public DateTime? Arrive_Date { get; set; }
        public DateTime? Leave_Date { get; set; }
        public int? Number_Children { get; set; }
        public int? Number_People { get; set; }
        public double? Price { get; set; }
        public double? Deposit { get; set; }
        public double? Discount { get; set; }
        public int? SysHotelID { get; set; }
        public int? KhungGio { get; set; }
        public int? Room_Type_ID { get; set; }
        public string LevelName { get; set; }
        public string Payment_TypeName { get; set; }
        public int? Payment_TypeID { get; set; }
        public string CountryName { get; set; }
        public int? CheckInID { get; set; }
        public int? roomid { get; set; }
        [Required]
        public string HotelName { get; set; }
        public string Note { get; set; }
        public double? Deduction { get; set; }
    }

	[Alias("Vw_InforCustomer_Room")]
    public partial class Vw_InforCustomer_Room 
    {
        [Required]
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public DateTime? DOB { get; set; }
        public string Company { get; set; }
        public int? CountryId { get; set; }
        [Required]
        public int CustomerTypeID { get; set; }
        public int? Sex { get; set; }
        public int? TeamMergeSTT { get; set; }
        public int? TeamSTT { get; set; }
        public string IdentifyNumber { get; set; }
        public string RoomName { get; set; }
        public int? KhungGio { get; set; }
        public string BookingCode { get; set; }
        public DateTime? Arrive_Date { get; set; }
        public DateTime? Leave_Date { get; set; }
        public int? Number_Children { get; set; }
        public int? Number_People { get; set; }
        public double? Price { get; set; }
        public double? Deposit { get; set; }
        public double? Discount { get; set; }
        public string LevelName { get; set; }
        public string Payment_TypeName { get; set; }
        public int? Payment_TypeID { get; set; }
        public string CountryName { get; set; }
    }

	[Alias("Vw_ProductService")]
    public partial class Vw_ProductService 
    {
        public string Name { get; set; }
        public int? productid { get; set; }
        [Required]
        public int cussvID { get; set; }
        public int? CheckinID { get; set; }
        public int? Quantity { get; set; }
        public double? TotalSale { get; set; }
        [Required]
        public double PriceOrder { get; set; }
        [Required]
        public double SalePrice { get; set; }
        public int? SysHotelID { get; set; }
        public DateTime? datecreated { get; set; }
        public int? status { get; set; }
        public int? UnitID { get; set; }
        [Required]
        public string UnitName { get; set; }
    }

	[Alias("Vw_PurchaseOrderDetail")]
    public partial class Vw_PurchaseOrderDetail 
    {
        [Required]
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public DateTime? InputDate { get; set; }
        public DateTime? DatePayment { get; set; }
        public int? SysHotelID { get; set; }
        [Required]
        public string SupplierName { get; set; }
        public string SupplierCode { get; set; }
        public int? StoreID { get; set; }
        [Required]
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        [Required]
        public string Unit { get; set; }
        public int? CateId { get; set; }
        [Required]
        public int SupplierID { get; set; }
        public int? Price { get; set; }
        public int? Quantity { get; set; }
        [Required]
        public int UnitId { get; set; }
        public DateTime? ManufactureDate { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public int? TypeOrder { get; set; }
    }

	[Alias("Vw_Report_TienPhong")]
    public partial class Vw_Report_TienPhong 
    {
        [Required]
        public int id { get; set; }
        public DateTime? DateCreated { get; set; }
        public int? SysHotelID { get; set; }
        public double? TotalAmount { get; set; }
        public int? TypeOrder { get; set; }
        public DateTime? CheckinDate { get; set; }
        public string Customername { get; set; }
        public string RoomNo { get; set; }
        public string RoomLevel { get; set; }
        [Required]
        public string BookingCode { get; set; }
    }

	[Alias("Vw_RoomActive")]
    public partial class Vw_RoomActive 
    {
        public string Name { get; set; }
        [AutoIncrement]
        public int ID { get; set; }
        public int? RoomLevel_ID { get; set; }
        public int? SysHotelID { get; set; }
    }

	[Alias("vw_RoomAvailable")]
    public partial class vw_RoomAvailable 
    {
        public int? status { get; set; }
        public int? roomid { get; set; }
        public string Name { get; set; }
        public DateTime? datePlanTo { get; set; }
        public DateTime? datePlanFrom { get; set; }
        public int? SysHotelID { get; set; }
    }

	[Alias("Vw_Store")]
    public partial class Vw_Store 
    {
        [Required]
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? DateOrder { get; set; }
        public string Description { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? QuotaMinimize { get; set; }
        [Required]
        public double SalePrice { get; set; }
        [Required]
        public int Status { get; set; }
        [Required]
        public int SupplierID { get; set; }
        public int? UnitID { get; set; }
        public int? ProductGroupID { get; set; }
        [Required]
        public string GroupName { get; set; }
        [Required]
        public string SupplierName { get; set; }
        [Required]
        public string UnitName { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        public int? TonKho { get; set; }
        public int? XuatKho { get; set; }
    }

	[Alias("Vw_Store_Pro")]
    public partial class Vw_Store_Pro 
    {
        [Required]
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? DateOrder { get; set; }
        public string Description { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? QuotaMinimize { get; set; }
        [Required]
        public double SalePrice { get; set; }
        [Required]
        public int Status { get; set; }
        [Required]
        public int SupplierID { get; set; }
        public int? UnitID { get; set; }
        public int? ProductGroupID { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        public int? StoreId { get; set; }
        public int? Limit { get; set; }
        public int? roomid { get; set; }
    }

	[Alias("Vw_Store1")]
    public partial class Vw_Store1 
    {
        [Required]
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? DateOrder { get; set; }
        public string Description { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? QuotaMinimize { get; set; }
        [Required]
        public double SalePrice { get; set; }
        [Required]
        public int Status { get; set; }
        [Required]
        public int SupplierID { get; set; }
        public int? UnitID { get; set; }
        public int? ProductGroupID { get; set; }
        [Required]
        public string GroupName { get; set; }
        [Required]
        public string SupplierName { get; set; }
        [Required]
        public string UnitName { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        public int? storeid { get; set; }
        public int? TonKho { get; set; }
        public int? XuatKho { get; set; }
    }

	[Alias("Vw_StoreConfig")]
    public partial class Vw_StoreConfig 
    {
        [Required]
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int? Createby { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? DateOrder { get; set; }
        public string Description { get; set; }
        public int? Modifyby { get; set; }
        public DateTime? ModifyDate { get; set; }
        public int? QuotaMinimize { get; set; }
        [Required]
        public double SalePrice { get; set; }
        [Required]
        public int Status { get; set; }
        [Required]
        public int SupplierID { get; set; }
        public int? UnitID { get; set; }
        public int? ProductGroupID { get; set; }
        [Required]
        public string GroupName { get; set; }
        [Required]
        public string SupplierName { get; set; }
        [Required]
        public string UnitName { get; set; }
        [Required]
        public int SysHotelID { get; set; }
        public int? storeid { get; set; }
        public int? TonKho { get; set; }
        public int? XuatKho { get; set; }
        public int? Limit { get; set; }
    }

	[Alias("Vw_TransferOrder")]
    public partial class Vw_TransferOrder 
    {
        [Required]
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public DateTime? InputDate { get; set; }
        public DateTime? DatePayment { get; set; }
        public int? SysHotelID { get; set; }
        [Required]
        public string SupplierName { get; set; }
        public string SupplierCode { get; set; }
        public int? StoreID { get; set; }
        [Required]
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        [Required]
        public string Unit { get; set; }
        public int? CateId { get; set; }
        [Required]
        public int SupplierID { get; set; }
        public int? Price { get; set; }
        public int? Quantity { get; set; }
        [Required]
        public int UnitId { get; set; }
        public int? FromStoreId { get; set; }
    }

}
#pragma warning restore 1591
